# -*- coding: utf-8 -*-
"""Untitled1.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XBoV0mU6MDBYh72rRkkc6naHkGpcXlv3
"""

import numpy as np
import pandas as pd
import io

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(io.StringIO(uploaded['SWE sample data - Q3 data.csv'].decode('utf-8')))
print(df)

#answer1
BDV_log = df[df["country_id"].isin(["BDV"])]
#del BDV_log["country_id"]
#del BDV_log["ts"]

BDV_log = BDV_log.drop_duplicates(["site_id","user_id"],keep="first")
BDV_log = BDV_log["site_id"].value_counts()
# print(BDV_log)
print(BDV_log.keys().tolist()[0],BDV_log[0])

#answer2

import datetime
df["ts"] = pd.to_datetime(df["ts"])
Between_3rd_and_4th = df[df["ts"]>datetime.datetime(2019,2,3,0,0,0)]
Between_3rd_and_4th = Between_3rd_and_4th[Between_3rd_and_4th["ts"]<datetime.datetime(2019,2,4,23,59)]

del Between_3rd_and_4th["ts"]
del Between_3rd_and_4th["country_id"]

Between_3rd_and_4th = Between_3rd_and_4th.groupby(["user_id","site_id"]).size().reset_index(name="number_of_visit")
Between_3rd_and_4th = Between_3rd_and_4th[Between_3rd_and_4th["number_of_visit"]>10]
print(Between_3rd_and_4th)

#answer3
df = df.sort_values(by="ts")
Popular_site = df.drop_duplicates(["user_id"],keep="last")
Popular_site = Popular_site.groupby(["site_id"]).size().reset_index(name="number_of_user").sort_values(by="number_of_user",ascending = False)
print(Popular_site[0:3])

#answer4
First_visit = df.drop_duplicates(["user_id"],keep="first").sort_values(by="user_id")
Last_visit = df.drop_duplicates(["user_id"],keep="last").sort_values(by="user_id")

Visit = pd.merge(First_visit,Last_visit,on="user_id")
Visit.columns = ["user_id","first_visit","last_visit"]

print(len(Visit[Visit["first_visit"]==Visit["last_visit"]]))

